import localFont from "next/font/local";
import "./globals.css";

const fontGlobal = localFont({
  src: "./fonts/PoltawskiNowy-Regular.otf",
  variable: "--font-global",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontGlobal.variable} antialiased`}>{children}</body>
    </html>
  );
}
